export const bdBurgers = [
    {id:1,name:"GENE CHEESE BURGER DOBLE", img:"https://resizer.glanacion.com/resizer/aDuSrK-kFy1v27LtOHPRYl4QlRs=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/RHVGX3MHVRB7VGEXBEVCCZHW5I.jpg",price:1350, type:"doble",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architectoLorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:2,name:"AMERICAN BURGER DOBLE", img:"https://resizer.glanacion.com/resizer/aDuSrK-kFy1v27LtOHPRYl4QlRs=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/RHVGX3MHVRB7VGEXBEVCCZHW5I.jpg", price:1450, type:"doble",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:3,name:"CHEESE BACON DOBLE", img:"https://resizer.glanacion.com/resizer/aDuSrK-kFy1v27LtOHPRYl4QlRs=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/RHVGX3MHVRB7VGEXBEVCCZHW5I.jpg", price:1550, type:"doble",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:4,name:"CHEESE BURGER DOBLE", img:"https://resizer.glanacion.com/resizer/aDuSrK-kFy1v27LtOHPRYl4QlRs=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/RHVGX3MHVRB7VGEXBEVCCZHW5I.jpg", price:1450, type:"doble",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:5,name:"CHEESE ONION DOBLE", img:"https://resizer.glanacion.com/resizer/aDuSrK-kFy1v27LtOHPRYl4QlRs=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/RHVGX3MHVRB7VGEXBEVCCZHW5I.jpg", price:1450, type:"doble",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:6,name:"CHEESE BURGER SIMPLE", img:"https://deananddennys.com/stage/contenidos/1612363992.jpg", price:1200, type:"simple",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:7,name:"CHEESE BACON SIMPLE", img:"https://deananddennys.com/stage/contenidos/1612363992.jpg", price:1300, type:"simple",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:8,name:"CHEESE BURGER SIMPLE", img:"https://deananddennys.com/stage/contenidos/1612363992.jpg", price:1200, type:"simple",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:9,name:"CHEESE ONION SIMPLE", img:"https://deananddennys.com/stage/contenidos/1612363992.jpg", price:1200, type:"simple",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:10,name:"AMERICAN BURGER TRIPLE", img:"https://st3.depositphotos.com/3957801/12810/i/600/depositphotos_128102518-stock-photo-big-beef-burger.jpg", price:1550, type:"triple",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:11,name:"CHEESE BACON TRIPLE", img:"https://st3.depositphotos.com/3957801/12810/i/600/depositphotos_128102518-stock-photo-big-beef-burger.jpg", price:1650, type:"triple",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:12,name:"A.K.A VEGGIE BURGER (DOBLE)", img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/halloumi-burger-4fdad97.jpg?quality=90&resize=500,454", price:1500, type:"not",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:13,name:"BANDEJA DE PAPAS", img:"https://cdn2.cocinadelirante.com/sites/default/files/styles/gallerie/public/images/2020/06/papas-fritas-con-maicena-facil.jpg", price:450, type:"potato",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    {id:14,name:"BANDEJA DE PAPAS CON CHEDDAR", img:"https://cdn2.cocinadelirante.com/sites/default/files/styles/gallerie/public/images/2020/06/papas-fritas-con-maicena-facil.jpg", price:500, type:"potato",info:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad atque, aperiam earum veritatis eveniet aliquam illo rerum, dolores voluptatibus praesentium numquam eos labore modi qui illum quasi temporibus, voluptas architecto", cantidad:1},
    
]